### ISSUE TITLE
Little typo errors and path errors

### ISSUE THREAD

**Issue by FrankUrbach** [chkwon/jpor_codes#5]
I've had revisited your code and recognized some brackets are missed in statements using ..Optimizer. In Julia v1.4 reading CSV-files with readdlm does not work with only the filename. using Base.joinpath could solve the problem. 
Best Frank

**Comment by chkwon** [comment]
Oops. Thanks! 

I couldn't see the issue with `readdlm`.  I think it depends on which directory you run julia from.  If I'm wrong, please let me know.

**Comment by chkwon** [comment]
Fixed by 3530040b3fbc22a3e1d620e11b8d524d4c399bb0

**Comment by FrankUrbach** [comment]
Sure. It depends on the directory, where you work with Julia.
I use Julia with the Atom editor and juno. If you open the file in the editor an run the script you get an error from the file loading. If your readers want play a little bit with your code the usage of the editor is better because you can write code with code-completion. This is why I used the joinpath function. 
It comes to my mind that providing a juypiter-notebook with the code and some little explanations.would be great for your readers.
Just an idea.

Shears
Frank

**Comment by chkwon** [comment]
Thanks for suggestions, Frank.  I'll consider such changes.  Jupyter notebooks will be certainly helpful, but at this moment, Julia and JuMP are evolving very quickly. Maintaining all those (book, code, notebook, etc) will require too much time from me. I will definitely consider jupyter notebooks later.

**Comment by FrankUrbach** [comment]
If you want, give me a hint, if you have a new version of your work and want some revisiting. This repository is a good starting point for somebody who doesn’t know much about JuMP and solving optimization problems.

Best
Frank
