### ISSUE TITLE
using  DelimitedFiles with title of the  header

### ISSUE THREAD

**Issue by linkhochon** [chkwon/jpor_codes#7]
In the `ssp_example1.jl` is there any way to read the data from the title of the header? I mean, instead of `start_node = round.(Int64, data[:,1])` is there another way to say start_node  is the one in the .csv file that its header is "start node i"

```
# Data Preparation
network_data_file = "simple_network.csv"
network_data = readdlm(network_data_file, ',', header=true)
data = network_data[1]
header = network_data[2]

```

![image](https://user-images.githubusercontent.com/29150324/157508634-33e5d331-cbda-47b4-b635-4a5560f5b957.png)

**Comment by chkwon** [comment]
You can use [CSV.jl](https://github.com/JuliaData/CSV.jl).

Try
```
using CSV
network_data = CSV.File(network_data_file)
network_data["start_node"]
```

**Comment by linkhochon** [comment]
Thanks @chkwon
