### ISSUE TITLE
Chaoter 6 , ssp_example1.jl or ssp_example1.jl expansion?

### ISSUE THREAD

**Issue by yaodaov** [chkwon/jpor_codes#8]
Hi!

How is it possible to extend the code in ssp_example1.jl or ssp_example1.jl to return "k" first shortest path from o to d and not just the first shortest?

I thank you and appreciate any advice.

**Comment by chkwon** [comment]
See this: https://en.wikipedia.org/wiki/Yen%27s_algorithm

**Comment by yaodaov** [comment]
Hi again, Thanks for the link. I knew about this and there is an instance of it in graph package (which is not working correctly). That's why I searched and find your program. I am very new to programming, and just wanted to know how to think to modify yours to something that gives k shortest path??

**Comment by chkwon** [comment]
```julia
using Graphs, SimpleWeightedGraphs

g = SimpleWeightedGraph(6) # Use `SimpleWeightedDiGraph` if directed.
add_edge!(g, 1, 2, 3)
add_edge!(g, 1, 3, 1)
add_edge!(g, 2, 4, 2)
add_edge!(g, 3, 4, 3)
add_edge!(g, 3, 5, 2)
add_edge!(g, 4, 6, 4)
add_edge!(g, 5, 6, 2)

K = 3
result = yen_k_shortest_paths(g, 1, 6, weights(g), K)

@show result.dists
@show result.paths
```
Here is an example.


See [here](https://juliagraphs.org/Graphs.jl/dev/algorithms/shortestpaths/#Graphs.yen_k_shortest_paths-Union{Tuple{T},%20Tuple{U},%20Tuple{AbstractGraph,%20U,%20U},%20Tuple{AbstractGraph,%20U,%20U,%20AbstractMatrix{T}},%20Tuple{AbstractGraph,%20U,%20U,%20AbstractMatrix{T},%20Int64}}%20where%20{U%3C:Integer,%20T%3C:Real}).
